### ISSUE TITLE
Support React 16.14 and above

### ISSUE THREAD

**Issue by stevenweaver** [stephenshank/react-phylotree#9]
Thanks!

**Comment by stephenshank** [comment]
Closing since it already does. At the present moment, hyphy-vision uses version `16.14.0`:

![image](https://user-images.githubusercontent.com/8673708/137753553-6fd79c91-57fc-492a-bd6f-acf3ce4e1424.png)

and the hyphy-vision SLAC widget consumes `react-phylotree` and is currently functional:
http://vision.hyphy.org/SLAC
